<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="modular_robot">

  <xacro:include filename="module.xacro" />
  <xacro:include filename="base.xacro" />

  <xacro:property name="flat_half_x" value="${0.0747 / 2.0}" />
  <xacro:property name="emerge_half_x" value="${0.0305 / 2.0}" />
  <xacro:property name="base_offset" value="${flat_half_x + emerge_half_x}" />

  <xacro:base name="base" />
  <xacro:module name="plus" />
  <xacro:module name="minus" />
  <xacro:module name="y" />

  <joint name="joint_x_plus" type="fixed">
    <parent link="base_link" />
    <child link="plus_connector_link" />
    <origin xyz="${base_offset} 0 0" rpy="0 0 0" />
  </joint>

  <joint name="joint_x_minus" type="fixed">
    <parent link="base_link" />
    <child link="minus_connector_link" />
    <origin xyz="${-1 * base_offset} 0 0" rpy="0 0 ${pi}" />
  </joint>

  <joint name="joint_y" type="fixed">
    <parent link="minus_motor_link" />
    <child link="y_connector_link" />
    <origin xyz="0.038125 0 0" rpy="0 0 0" />
  </joint>
</robot>